name: thingy52
version: "1.0"
base: core18
summary: Connect with Nordic Thingy52
description: |
  Connect over BLE using bluez with a Nordic Thingy52.

grade: stable
confinement: strict

apps:
  thingy52:
    command: python3 $SNAP/bin/thingy52
    plugs:
      - bluetooth-control
      - network
      - network-bind
  find:
    command: python3 $SNAP/bin/find-thingy52.py
    plugs:
      - bluetooth-control
      - network
      - network-bind

parts:
  find-thingy52-script:
    source: scripts
    plugin: dump
  bluepy:
    plugin: python
    source: https://github.com/IanHarvey/bluepy.git
    source-tag: "v/1.3.0"
    build-packages: [build-essential, libglib2.0-dev]
