name: thingy52
version: "1.0"
base: core18
summary: Connect with Nordic Thingy52
description: |
  Connect over BLE using bluez with a Nordic Thingy52.

# use snapd 2.45 as a reference point for modern snapd's, since there
# are really old snapd's out there on i.e. raspian which don't work
# when this snap is the first one installed, missing the core snap
# from being installed and thus having no interfaces available
assumes: [snapd2.45]

grade: stable
confinement: strict

apps:
  thingy52:
    command: python3 $SNAP/bin/thingy52
    plugs:
      - bluetooth-control
      - network
      - network-bind
  find:
    command: python3 $SNAP/bin/find-thingy52.py
    plugs:
      - bluetooth-control
      - network
      - network-bind

parts:
  find-thingy52-script:
    source: scripts
    plugin: dump
  bluepy:
    plugin: python
    source: https://github.com/IanHarvey/bluepy.git
    source-tag: "v/1.3.0"
    build-packages: [build-essential, libglib2.0-dev]
